//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_LibraryOwner.WCF_LibraryManager {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/WCF_BookLibrary")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBorrowedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsbnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBorrowed {
            get {
                return this.IsBorrowedField;
            }
            set {
                if ((this.IsBorrowedField.Equals(value) != true)) {
                    this.IsBorrowedField = value;
                    this.RaisePropertyChanged("IsBorrowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isbn {
            get {
                return this.IsbnField;
            }
            set {
                if ((object.ReferenceEquals(this.IsbnField, value) != true)) {
                    this.IsbnField = value;
                    this.RaisePropertyChanged("Isbn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_LibraryManager.ILibraryManager")]
    public interface ILibraryManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/AddBook", ReplyAction="http://tempuri.org/ILibraryManager/AddBookResponse")]
        void AddBook(string isbn, string code, string title, string author, string subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/AddBook", ReplyAction="http://tempuri.org/ILibraryManager/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(string isbn, string code, string title, string author, string subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/GetAllBooks", ReplyAction="http://tempuri.org/ILibraryManager/GetAllBooksResponse")]
        System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book> GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/GetAllBooks", ReplyAction="http://tempuri.org/ILibraryManager/GetAllBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book>> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/GetBooksBySubject", ReplyAction="http://tempuri.org/ILibraryManager/GetBooksBySubjectResponse")]
        System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book> GetBooksBySubject(string subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/GetBooksBySubject", ReplyAction="http://tempuri.org/ILibraryManager/GetBooksBySubjectResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book>> GetBooksBySubjectAsync(string subject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/GetBooksByAuthor", ReplyAction="http://tempuri.org/ILibraryManager/GetBooksByAuthorResponse")]
        System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book> GetBooksByAuthor(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/GetBooksByAuthor", ReplyAction="http://tempuri.org/ILibraryManager/GetBooksByAuthorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book>> GetBooksByAuthorAsync(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/GetBooksByCode", ReplyAction="http://tempuri.org/ILibraryManager/GetBooksByCodeResponse")]
        Console_LibraryOwner.WCF_LibraryManager.Book GetBooksByCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/GetBooksByCode", ReplyAction="http://tempuri.org/ILibraryManager/GetBooksByCodeResponse")]
        System.Threading.Tasks.Task<Console_LibraryOwner.WCF_LibraryManager.Book> GetBooksByCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/UpdateToBorrowed", ReplyAction="http://tempuri.org/ILibraryManager/UpdateToBorrowedResponse")]
        void UpdateToBorrowed(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/UpdateToBorrowed", ReplyAction="http://tempuri.org/ILibraryManager/UpdateToBorrowedResponse")]
        System.Threading.Tasks.Task UpdateToBorrowedAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/UpdateToAvaible", ReplyAction="http://tempuri.org/ILibraryManager/UpdateToAvaibleResponse")]
        void UpdateToAvaible(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryManager/UpdateToAvaible", ReplyAction="http://tempuri.org/ILibraryManager/UpdateToAvaibleResponse")]
        System.Threading.Tasks.Task UpdateToAvaibleAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibraryManagerChannel : Console_LibraryOwner.WCF_LibraryManager.ILibraryManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibraryManagerClient : System.ServiceModel.ClientBase<Console_LibraryOwner.WCF_LibraryManager.ILibraryManager>, Console_LibraryOwner.WCF_LibraryManager.ILibraryManager {
        
        public LibraryManagerClient() {
        }
        
        public LibraryManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibraryManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibraryManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddBook(string isbn, string code, string title, string author, string subject) {
            base.Channel.AddBook(isbn, code, title, author, subject);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(string isbn, string code, string title, string author, string subject) {
            return base.Channel.AddBookAsync(isbn, code, title, author, subject);
        }
        
        public System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book> GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book>> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book> GetBooksBySubject(string subject) {
            return base.Channel.GetBooksBySubject(subject);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book>> GetBooksBySubjectAsync(string subject) {
            return base.Channel.GetBooksBySubjectAsync(subject);
        }
        
        public System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book> GetBooksByAuthor(string author) {
            return base.Channel.GetBooksByAuthor(author);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Console_LibraryOwner.WCF_LibraryManager.Book>> GetBooksByAuthorAsync(string author) {
            return base.Channel.GetBooksByAuthorAsync(author);
        }
        
        public Console_LibraryOwner.WCF_LibraryManager.Book GetBooksByCode(string code) {
            return base.Channel.GetBooksByCode(code);
        }
        
        public System.Threading.Tasks.Task<Console_LibraryOwner.WCF_LibraryManager.Book> GetBooksByCodeAsync(string code) {
            return base.Channel.GetBooksByCodeAsync(code);
        }
        
        public void UpdateToBorrowed(System.Guid id) {
            base.Channel.UpdateToBorrowed(id);
        }
        
        public System.Threading.Tasks.Task UpdateToBorrowedAsync(System.Guid id) {
            return base.Channel.UpdateToBorrowedAsync(id);
        }
        
        public void UpdateToAvaible(System.Guid id) {
            base.Channel.UpdateToAvaible(id);
        }
        
        public System.Threading.Tasks.Task UpdateToAvaibleAsync(System.Guid id) {
            return base.Channel.UpdateToAvaibleAsync(id);
        }
    }
}
